name: Build Flashcards on PDF push

on:
  push:
    paths:
      - 'data/pdf/**.pdf'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      # S'assurer d'avoir les *vrais* PDFs (pas des pointeurs LFS)
      - name: Ensure LFS files are present
        run: |
          git lfs pull
          git lfs checkout
          git lfs ls-files -l || true

      # Installer Tesseract + packs de langue (eng obligatoire, fra recommandé)
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-fra

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (Python)
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf pymupdf4llm sentence-transformers faiss-cpu numpy tqdm openai genanki Pillow pytesseract

      - name: Generate flashcards (OpenAI)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python tools/make_qa.py --course "SYE"

      - name: Debug listing
        run: |
          echo "Tree after generation:"
          ls -R

      - name: Commit outputs
        run: |
          git config user.name "flashcards-bot"
          git config user.email "bot@users.noreply.github.com"
          mkdir -p notes anki
          git add -f notes anki || true
          git commit -m "auto: flashcards updated" || echo "nothing to commit"
          git push
