name: Build Flashcards on PDF push
on:
  push:
    paths:
      - 'data/pdf/**.pdf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf pymupdf4llm sentence-transformers faiss-cpu numpy genanki tqdm ollama openai
      - name: (Option) Start Ollama & pull model
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          sleep 4
          ollama pull llama3.1:8b-instruct
      - name: Generate flashcards
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # si tu utilises OpenAI
        run: |
          python tools/make_qa.py --course "SYE"
      - name: Commit outputs
        run: |
          git config user.name "flashcards-bot"
          git config user.email "bot@users.noreply.github.com"
          git add notes anki || true
          git commit -m "auto: flashcards updated" || echo "nothing to commit"
          git push