name: Build Flashcards on PDF push

on:
  push:
    paths:
      - 'data/pdf/**.pdf'
  workflow_dispatch:

permissions:
  contents: write   # <-- donne le droit de pousser sur le repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf pymupdf4llm sentence-transformers faiss-cpu numpy tqdm openai genanki

      - name: Generate flashcards (OpenAI)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python tools/make_qa.py --course "SYE"

      - name: Commit outputs
        run: |
          git config user.name "flashcards-bot"
          git config user.email "bot@users.noreply.github.com"
          git add notes anki || true
          git commit -m "auto: flashcards updated" || echo "nothing to commit"
          git push
